version: '3.6'
services:

   webtop:
      image: "{{ helx_registry }}/helxplatform/webtop/base:v0.0.2"
      container_name: webtop
      entrypoint: /init
      ports:
        - 3000:3000
      volumes:
         - pvc://pjl-projects-helx-sterling-tmp-pvc:/projects/helx/sterling-tmp
      deploy:
        resources:
          limits:
            cpus: '4'
            memory: 2048M
          reservations:
            cpus: '.5'
            memory: 1024M 
