version: '3.6'
services:

   webtop:
      image: "{{ helx_registry }}/helxplatform/webtop/base:v0.0.2"
      container_name: webtop
      entrypoint: /init
      ports:
        - 3000:3000
      volumes:
         - pvc://helx-sidecar-test/sidecar:/sidecar
      deploy:
        resources:
          limits:
            cpus: '4'
            memory: 2048M
          reservations:
            cpus: '1.5'
            memory: 1024M 
