version: '3.7'
services:
  atlas:
    image: containers.renci.org/helxplatform/ohdsi-atlas:test-0.1.0
    ports:
      - 8081:8081
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000M
        reservations:
          cpus: '1'
          memory: 2000M
  webapi:
    env:
      - DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - DATASOURCE_OHDSI_SCHEMA=webapi
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=webapi
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_BATCH_REPOSITORY_TABLEPREFIX=webapi.BATCH_
      - FLYWAY_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - FLYWAY_SCHEMAS=webapi
      - FLYWAY_PLACEHOLDERS_OHDSISCHEMA=webapi
      - SECURITY_PROVIDER=DisabledSecurity
    image: containers.renci.org/helxplatform/ohdsi-webapi:dev-0.2.0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000M
        reservations:
          cpus: '1'
          memory: 2000M
