---
# Docker compose formatted system.
version: "3"
services:
  rstudio-rocker:
    image: "containers.renci.org/helxplatform/rstudio:0.1.6"
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        reservations:
          cpus: '1'
          memory: 2048M 
