version: "3"
services:
  jupyter-helx-tensorflow-nb:
    # image: "docker.io/helxplatform/helx-tensorflow-notebook:v0.1.2"
    image: "docker.io/helxplatform/tensorflow-notebook:develop"
    ports:
      - 8888:8888
    volumes:
      - pvc://projects-pvc:/projects
    env:
      - TF_ENABLE_ONEDNN_OPTS=0
      - TF_CPP_MIN_LOG_LEVEL='2'
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8000M
          ephemeralStorage: 512M
        reservations:
          cpus: "1"
          memory: 4000M
          ephemeralStorage: 128M
