version: "3"
services:
  jupyter-helx-tensorflow-nb:
    image: "{{ helx_registry }}/helxplatform/jupyter/helx-tensorflow-notebook:a0f5b86-202305201724-dirty"
    ports:
      - 8888:8888
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
          ephemeralstorage: 4096Mi
          # gpus: '1'
          # nvidia.com/gpu: 1
          # nvidia.com/mig-1g.5gb: 1
          devices:
            - capabilities: ["gpu"]
              count: "1"
          # devices:
          #   - capabilities: "gpu"
          #     count: 1
          # devices:
          #   capabilities: "gpu"
          #   count: "1"
        reservations:
          cpus: '.5'
          memory: 250M
          ephemeralstorage: 256Mi
          # gpus: '0'
          # nvidia.com/gpu: 1
          devices:
            - capabilities: ["gpu"]
              count: "0"
          # devices:
          #   - capabilities: "gpu"
          #     count: 0
          # devices:
          #   capabilities: "gpu"
          #   count: "0"
