version: "3"
services:
  jupyter-helx-tensorflow-nb:
    image: "{{ helx_registry }}/helxplatform/jupyter/helx-tensorflow-notebook:v0.1.0"
    ports:
      - 8888:8888
    volumes:
        - pvc://projects-pvc:/projects
    # These env vars might be good if a GPU is not in use.  Maybe other times too.
    # env:
    #   - TF_ENABLE_ONEDNN_OPTS=0
    #   - TF_CPP_MIN_LOG_LEVEL='2'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8192M
          ephemeralStorage: 4096Mi
          devices:
            - capabilities: ["gpu"]
              count: "1"
        reservations:
          cpus: '.5'
          memory: 250M
          ephemeralStorage: 256Mi
          devices:
            - capabilities: ["gpu"]
              count: "0"
