version: "3"
services:
  jupyter-helx-tensorflow-nb:
    image: "{{ helx_registry }}/helxplatform/jupyter/helx-tensorflow-notebook:f7d9bba-202306231436"
    ports:
      - 8888:8888
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
          ephemeralStorage: 512Mi
          devices:
            - capabilities: ["gpu"]
              count: "1"
        reservations:
          cpus: '.5'
          memory: 250M
          ephemeralStorage: 128Mi
          devices:
            - capabilities: ["gpu"]
              count: "0"