version: "0.0.1"
services:
  jupyter-helx-tensorflow-nb:
    image: "containers.renci.org/helxplatform/jupyter/helx-tensorflow-notebook:v0.2.1"
    container_name: jupyter-lab
    ports:
      - 8888:8888
    volumes:
      - pvc://projects-ees-pvc:/projects/ees
#      - pvc://stdnfs:/tmp
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 64000M
          ephemeralStorage: 1024Mi
          devices:
            - capabilities: ["gpu"]
              count: "1"
        reservations:
          cpus: '1'
          memory: 5000M
          ephemeralStorage: 256Mi
          devices:
            - capabilities: ["gpu"]
              count: "0"
