version: "3"
services:
  vs-code:
    image: "{{ helx_registry }}/helxplatform/third-party/vs-code:v0.0.9"
    ports:
      - 8080:8080
    #proxy-rewrite-rule: false
    #proxy_rewrite:
    #  enabled: True
    #  target: /
    # Use Dockerfile entrypoint but this set of command args
    #entrypoint: [ "/bin/sh", "-c", "sleep infinity" ]
    #entrypoint:
    command:
      - /usr/bin/entrypoint.sh
      - --bind-addr
      - 0.0.0.0:8080
      - --auth
      - none
      - --cert
      - "false"
      - /home/$$USER
    volumes:
      - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8192M
        reservations:
          cpus: "2"
          memory: 8192M
