version: "3"
services:
  vs-code:
    image: "{{ helx_registry }}/helxplatform/third-party/vs-code:v0.0.4"
    ports:
      - 8080:8080
    # Use Dockerfile entrypoint but this set of command args
    # entrypoint:
    command:
      - --bind-addr
      - 0.0.0.0:8080
      - --auth
      - none
      - --cert
      - "false"
      - /home/$$USER
    # Remove? #
    volumes:
      - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8192M
        reservations:
          cpus: "1"
          memory: 8192M
