---
# Docker compose formatted system.
# NOTE: NB_PREFIX has to be set to "/" as an environment variable if running locally.
# If running via tycho from HeLx AppStore, tycho will set the variable.
version: "3"
services:
  jupyter-datascience-db:
    image: "{{ helx_registry }}/helxplatform/jupyter-datascience-db:v0.0.16"
    entrypoint:
      - /usr/local/bin/start-jupyter-datascience-db.sh
    ports:
      - 8888:8888
    volumes:
         - pvc://helx-sidecar-test/sidecar:/sidecar
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '.5'
          memory: 256M 
