version: '3.6'
services:
  pgadmin:
    image: "containers.renci.org/helxplatform/pgadmin4:202305082150"
    container_name: pgadmin
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M
        reservations:
          cpus: '2'
          memory: 8192M
