version: '3.6'
services:
  pgadmin:
    image: "docker.io/dpage/pgadmin4:2023-01-16-3"
    container_name: pgadmin
    entrypoint:
      - /bin/sh
      - -c
      - SCRIPT_NAME="$NB_PREFIX" /entrypoint.sh
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M
        reservations:
          cpus: '.5'
          memory: 512M 
