version: '3.6'
services:
  pgadmin:
    image: "containers.renci.org/helxplatform/pgadmin4:202302062059"
    container_name: pgadmin
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '.1'
          memory: 50M
