version: '3.6'
services:
  pgadmin:
    image: "containers.renci.org/helxplatform/pgadmin4:202302061714"
    container_name: pgadmin
    # entrypoint:
    #   - /bin/sh
    #   - -c
    #   - /start-pgadmin.sh
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M
        reservations:
          cpus: '2'
          memory: 8192M
