version: '3.6'
services:
  pgadmin:
    image: "muralikarthikk/hex-pgadmin:0.1"
    container_name: pgadmin
    entrypoint:
      - /bin/sh
      - -c
      - start-pgadmin.sh
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M
        reservations:
          cpus: '.5'
          memory: 512M 
