version: "3"
services:
  jupyter-r-notebook:
    image: "{{ helx_registry }}/helxplatform/jupyter/helx-r-notebook:latest"
    ports:
      - 8888:8888
    volumes:
      - pvc://projects-ees-pvc:/projects/ees
      - pvc://projects-prediction-work-pvc:/projects/prediction_work
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '.5'
          memory: 256M
