version: "3"
services:
  jupyter-helx-notebook:
    # image: "{{ helx_registry }}/helxplatform/jupyter/helx-notebook:0.0.2"
    image: "{{ helx_registry }}/helxplatform/jupyter/helx-notebook:tensorflow-python-3.8"
    ports:
      - 8888:8888
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '.5'
          memory: 256M
