version: "3"
services:
  jupyter-helx-notebook:
    image: "{{ helx_registry }}/helxplatform/jupyter/helx-notebook:ordrd-v0.0.3"
    ports:
      - 8888:8888
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 10G
        reservations:
          cpus: '2'
          memory: 10G

