version: "3"
services:
  jupyter-helx-notebook:
    image: "{{ helx_registry }}/helxplatform/jupyter/helx-notebook:v0.1.5"
    ports:
      - 8888:8888
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 8Gi
        reservations:
          cpus: '2'
          memory: 2Gi

