version: "3"
services:
  jupyter-helx-notebook:
    image: "containers.renci.org/helxplatform/jupyter/helx-tensorflow-notebook:v0.2.1"
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8000M
        reservations:
          cpus: '.5'
          memory: 8000M
