version: "3"
services:
  jupyter-helx-notebook:
    image: "{{ helx_registry }}/helxplatform/jupyter/helx-notebook:latest"
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '.5'
          memory: 250M
