version: "3.6"
services:
  scout:
    image: muralikarthikk/cloudtop-scout:0.1.1.alpha.2
    container_name: scout
    entrypoint: /init
    ports:
      - 8080:8080
    volumes:
      - pvc://nfsrods:/nfsrods
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4000M
        reservations:
          cpus: '2'
          memory: 4000M
