---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server-w-nginx:
    # image: "containers.renci.org/helxplatform/rstudio-server:v0.0.1"
    # image: "containers.renci.org/helxplatform/rstudio-server:806cbbe-202310061350-dirty"
    image: "containers.renci.org/helxplatform/rstudio-server:latest"
    ports:
      - 8080:8080
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
        resources:
          limits:
            cpus: '2'
            memory: 2048M
          reservations:
            cpus: '.5'
            memory: 1024M
  nginx:
    image: "containers.renci.org/helxplatform/rstudio-server-nginx:latest"
    env:
    - RSTUDIO_SERVER_HOST=localhost
    - RSTUDIO_SERVER_PORT=8787
    - DELETE_DEFAULT_USER_HOME_IF_UNUSED="no"
    - RSTUDIO_SERVER_BASE_PATH="/"
    - RSTUDIO_LOG_LEVEL="debug"
    deploy:
      resources:
        limits:
          cpus: 150m
          memory: 256Mi
      reservations:
          cpus: 75m
          memory: 128Mi
