---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server-w-nginx:
    # image: "containers.renci.org/helxplatform/rstudio-server:v0.0.1"
    # image: "containers.renci.org/helxplatform/rstudio-server:806cbbe-202310061350-dirty"
    image: "containers.renci.org/helxplatform/rstudio-server:host-path-root"
    ports:
      - 8888:8888
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
        resources:
          limits:
            cpus: '2'
            memory: 2048M
          reservations:
            cpus: '.5'
            memory: 1024M
  rstudio-server-nginx:
    image: "containers.renci.org/helxplatform/rstudio-server-nginx:11b8d84-202310091944-dirty"
    env:
    - RSTUDIO_SERVER_HOST=localhost
    - RSTUDIO_SERVER_PORT=8787
    deploy:
      resources:
        limits:
          cpus: 150m
          memory: 256Mi
      reservations:
          cpus: 75m
          memory: 128Mi
