version: '3.6'
services:

   cloud-top:
      # image: "{{ helx_registry }}/helxplatform/cloudtop:develop-v0.0.43"
      # image: "linuxserver/webtop"
      image: "lscr.io/linuxserver/webtop:ubuntu-mate"
      container_name: cloud-top
      entrypoint: /init
      ports:
        - 3000:3000
      volumes:
         - pvc://helx-sidecar-test/sidecar:/sidecar
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: 2048M
          reservations:
            cpus: '0.5'
            memory: 512M 
