version: '3.6'
services:

   cloud-top:
      image: "{{ third_party_registry }}/helxplatform/cloudtop:64ed536"
      container_name: cloud-top
      entrypoint: /init
      ports:
        - 8080:8080
      volumes:
         - pvc://helx-sidecar-test/sidecar:/sidecar
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 2000M
          reservations:
            cpus: '0.5'
            memory: 2000M 
