version: '3.6'
services:

   cloud-top:
      image: "{{ helx_registry }}/helxplatform/cloudtop:develop-v0.0.43"
      image: "containers.renci.org/helxplatform/webtop/base:latest"
      container_name: cloud-top
      entrypoint: /init
      ports:
        - 8080:8080
      volumes:
         - pvc://helx-sidecar-test/sidecar:/sidecar
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 2000M
          reservations:
            cpus: '0.5'
            memory: 2000M 
