version: '3.6'
services:

   webtop-octave:
      image: "{{ helx_registry }}/helxplatform/webtop/octave:202301181033"
      container_name: webtop-octave
      entrypoint: /init
      ports:
        - 3000:3000
      volumes:
         - pvc://helx-sidecar-test/sidecar:/sidecar
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: 2048M
          reservations:
            cpus: '1'
            memory: 1024M 
