version: '3.6'
services:

   webtop-octave:
      image: "{{ helx_registry }}/helxplatform/webtop/octave:v0.0.2"
      container_name: webtop-octave
      entrypoint: /init
      ports:
        - 3000:3000
      volumes:
         - pvc://helx-sidecar-test/sidecar:/sidecar
      deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '.1'
          memory: 50M
