version: "3"
services:
  jupyter-lab:
    image: helxplatform/jupyter-lab:use-base-helx-notebook"
    container_name: jupyter-lab
    # user: "30000:1136"
    # entrypoint:
    #   - /bin/bash
    #   - -c
    #   - start-jupyter-lab.sh
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4000M
        reservations:
          cpus: "1"
          memory: 4000M
