version: "0.0.1"
services:
  jupyter-lab:
    image: "containers.renci.org/helxplatform/jupyter/minimal-poetry-notebook:v0.0.6"
    container_name: jupyter-lab
    entrypoint:
      - /bin/bash
      - -c
      - start-jupyter-lab.sh
    ports:
      - 8888:8888
    volumes:
      - pvc://projects-ees-pvc:/projects/ees
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 64000M
          devices:
            - capabilities: [ "gpu" ]
              count: "1"
        reservations:
          cpus: '1'
          memory: 1000M
          devices:
            - capabilities: ["gpu"]
              count: "0"
