version: "3"
services:
  jupyter-lab:
    image: "{{ helx_registry }}/helxplatform/jupyter-lab:jupyter-helx-notebook-base"
    container_name: jupyter-lab
    # user: "30000:0"
    # entrypoint:
    #   - /bin/bash
    #   - -c
    #   - start-jupyter-lab.sh
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4000M
        reservations:
          cpus: "1"
          memory: 4000M
