version: "0.1.0"
services:
  jupyter-lab:
    image: "{{ helx_registry }}/helxplatform/jupyter/helx-notebook/eduhelx-data720:0.0.1"
    container_name: jupyter-lab
    user: "1001:0"
    entrypoint:
      - /init.sh
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8000M
        reservations:
          cpus: "1"
          memory: 4000M
