version: "0.1.0"
services:
  jupyter-lab:
    image: "{{ helx_registry }}/helxplatform/jupyter-lab:latest"
    pull_policy: always
    container_name: jupyter-lab
    user: "1000800040:0"
    entrypoint:
      - /bin/bash
      - -c
      - start-jupyter-lab.sh
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 6000M
        reservations:
          cpus: "1"
          memory: 6000M
