---
# Docker compose formatted system.
version: "3"
services:
  sas-studio:
    image: "{{ helx_registry }}/helxplatform/sas-studio:0.0.1"
    ports:
      - 38080:38080
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 64000M
        reservations:
          cpus: '2'
          memory: 2000M
