---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server:
    image: "containers.renci.org/helxplatform/rstudio-server:v0.0.1"
    ports:
      - 8787:8787
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
        resources:
          limits:
            cpus: '2'
            memory: 10000M
          reservations:
            cpus: '2'
            memory: 10000M
