---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server:
    image: "containers.renci.org/helxplatform/rstudio-server:v0.0.1"
    ports:
      - 8787:8787
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '.1'
          memory: 50M
