---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server:
    image: "containers.renci.org/helxplatform/rstudio:0.1.1"
    ports:
      - 8787:8787
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000M
        reservations:
          cpus: '1'
          memory: 1000M 
