---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server:
    image: "containers.renci.org/helxplatform/rstudio-server:ordrd-v0.0.2"
    # env:
    #   - DELETE_DEFAULT_USER_HOME_IF_UNUSED=no
    #   - RSTUDIO_LOG_LEVEL=debug
    ports:
      - 8787:8787
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
        resources:
          limits:
            cpus: '2'
            memory: 8000M
          reservations:
            cpus: '1'
            memory: 1000M
