---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server:
    image: "containers.renci.org/helxplatform/rstudio:0.1.6"
    ports:
      - 8080:8080
    volumes:
        - pvc://eduhelx-sandbox-projects-pvc:/projects
        - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        reservations:
          cpus: '1'
          memory: 2048M 
