---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server:
    image: "containers.renci.org/helxplatform/rstudio-server:v0.2.2"
    ports:
      - 8787:8787
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
        resources:
          limits:
            cpus: '8'
            memory: 12Gi
          reservations:
            cpus: '1'
            memory: 2Gi
