version: "3"
services:
  palimpzest-biome:
    image: "docker.io/frostyfan109/bdf-pz:3-13-26.0"
    ports:
      - 8888:8888
    volumes:
      - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 16384M
          ephemeralStorage: 4096Mi
        reservations:
          cpus: "1"
          memory: 4096M
          ephemeralStorage: 2048Mi
