version: "3"
services:
  biome:
    image: "{{ helx_registry }}/helxplatform/biome:10-31-25.0"
    ports:
      - 8888:8888
    volumes:
      - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 16384M
        reservations:
          cpus: "1"
          memory: 4096M
