version: "3"
services:
  biome:
    image: "docker.io/frostyfan109/bdf-pz:static-fixed.1"
    ports:
      - 8888:8888
    volumes:
      - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8192M
        reservations:
          cpus: "1"
          memory: 8192M
