version: "3"
services:
  slicer:
    image: "{{ helx_registry }}/helxplatform/slicer:b3db204-202310201226-dirty"
    ports:
      - 6901:6901
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8192M
          #ephemeralStorage: 4096Mi
          devices:
            - capabilities: ["gpu"]
              count: "1"
        reservations:
          cpus: '.5'
          memory: 250M
          #ephemeralStorage: 256Mi
          devices:
            - capabilities: ["gpu"]
              count: "0"
