version: "3"
services:
  nvidia-tensorflow:
    image: "{{ helx_registry }}/helxplatform/helx-nvidia-tensorflow:0.0.2"
    ports:
      - 8888:7681
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8192M
          ephemeralStorage: 4096Mi
          devices:
            - capabilities: ["gpu"]
              count: "1"
        reservations:
          cpus: '.5'
          memory: 250M
          ephemeralStorage: 256Mi
          devices:
            - capabilities: ["gpu"]
              count: "0"
