version: "3.0"
services:
  ohif-viewer:
    image: "{{ helx_registry }}/helxplatform/ohif-viewer:v0.1.0"
    container_name: ohif-viewer
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8000M
        reservations:
          cpus: "1"
          memory: 2000M
