version: '3.7'
services:
  ohdsi:
    env:
      - WEBAPI_URL=http://localhost:8080/WebAPI/
    image: containers.renci.org/helxplatform/ohdsi-atlas:test-0.1.1
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
        reservations:
          cpus: '0.5'
          memory: 200M
  webapi:
    env:
      - DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - DATASOURCE_OHDSI_SCHEMA=ohdsi
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=ohdsi
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_BATCH_REPOSITORY_TABLEPREFIX=ohdsi.BATCH_
      - FLYWAY_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - FLYWAY_SCHEMAS=ohdsi
      - FLYWAY_PLACEHOLDERS_OHDSISCHEMA=ohdsi
      - FLYWAY_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - FLYWAY_DATASOURCE_USERNAME=postgres
      - FLYWAY_DATASOURCE_PASSWORD=postgres
      - SECURITY_PROVIDER=DisabledSecurity
    image: ohdsi/webapi:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
        reservations:
          cpus: '0.5'
          memory: 200M
  postgres:
    env:
      - POSTGRES_PASSWORD=postgres
    image: postgres:14
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
        reservations:
          cpus: '0.5'
          memory: 200M
