version: '3.7'
services:
  atlas:
    environment:
      - WEBAPI_URL=http://localhost:8080/WebAPI/
    image: containers.renci.org/helxplatform/ohdsi-atlas:test-0.1.0
    ports:
      - 8080:8080
  webapi:
    container_name: webapi
    environment:
      - DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - DATASOURCE_OHDSI_SCHEMA=ohdsi
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=ohdsi
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_BATCH_REPOSITORY_TABLEPREFIX=ohdsi.BATCH_
      - FLYWAY_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - FLYWAY_SCHEMAS=ohdsi
      - FLYWAY_PLACEHOLDERS_OHDSISCHEMA=ohdsi
      - FLYWAY_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - FLYWAY_DATASOURCE_USERNAME=postgres
      - FLYWAY_DATASOURCE_PASSWORD=postgres
      - SECURITY_PROVIDER=DisabledSecurity
    image: ohdsi/webapi:latest
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:14
