version: '3.6'
services:

   webtop-pgadmin:
      image: "{{ helx_registry }}/helxplatform/webtop/pgadmin:202201111033"
      container_name: webtop-pgadmin
      entrypoint: /init
      ports:
        - 3000:3000
      volumes:
         - pvc://helx-sidecar-test/sidecar:/sidecar
      deploy:
        resources:
          limits:
            cpus: '1.5'
            memory: 2048M
          reservations:
            cpus: '1.5'
            memory: 2048M
