version: "3"
services:
 filebrowser:
  image: "{{ third_party_registry }}/hurlenko/filebrowser"
  ports:
   - 8080:8080
  entrypoint:
   - /bin/sh
   - -c
   - /filebrowser --noauth --root="/home" --address=0.0.0.0 --database=/config/filebrowser.db
  deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '.1'
          memory: 50M
