version: "3"
services:
  filebrowser:
    # image: "{{ helx_registry }}/helxplatform/third-party/filebrowser"
    image: "wateim/filebrowser:jeffw"
    ports:
      - 8080:8080
    entrypoint:
      - /bin/sh
      - -c
      # - /filebrowser --noauth --root="/home" --address=0.0.0.0 --database=/config/filebrowser.db
      - /filebrowser --noauth --root="/home" --address=0.0.0.0 --port=8080 --database=/home/${USER}/.filebrowser/filebrowser.db
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
        resources:
          limits:
            cpus: '2'
            memory: 2048M
          reservations:
            cpus: '.5'
            memory: 256M
