version: "3"
services:
  filebrowser:
    image: "filebrowser/filebrowser:v2.26.0"
    ports:
      - 8080:8080
    entrypoint:
      - /bin/sh
      - -c
      - /filebrowser --noauth --root=/home --port=8080 --address=0.0.0.0 --database=/home/{{ helx_user }}/.filebrowser/filebrowser.db
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
        resources:
          limits:
            cpus: '2'
            memory: 2048M
          reservations:
            cpus: '.5'
            memory: 1024M
