version: "3"
services:
  filebrowser:
    image: "{{ helx_registry }}/helxplatform/filebrowser:v.2.24.0"
    ports:
      - 8080:8080
    entrypoint:
      - /bin/sh
      - -c
      - /filebrowser --noauth --root="/home" --address=0.0.0.0 --database=/config/filebrowser.db
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
        resources:
          limits:
            cpus: '2'
            memory: 2048M
          reservations:
            cpus: '.5'
            memory: 1024M
