version: "3"
services:
  filebrowser:
    image: "containers.renci.org/helxplatform/third-party/filebrowser:v3.3.0"
#    image: "wateim/filebrowser:jeffw"
    ports:
      - 8080:8080
    entrypoint:
      - /bin/sh
      - -c
      - >
        ROOT_DIR=$(test -d /shared && echo "/home/${USER}" || echo "/home");
        exec tini -- /init.sh /filebrowser --noauth --root="${ROOT_DIR}" --address=0.0.0.0 --port=8080 --database=/home/${USER}/.filebrowser/filebrowser.db;
    volumes:
        - pvc://projects-pvc:/projects
    deploy:
        resources:
          limits:
            cpus: '2'
            memory: 2048M
          reservations:
            cpus: '.5'
            memory: 1024M
