version: "3"
services:
 filebrowser:
  image: "{{ third_party_registry }}/hurlenko/filebrowser"
  ports:
   - 8080:8080
  entrypoint:
   - /bin/sh
   - -c
   - /filebrowser --noauth --root="/home" --address=0.0.0.0 --database=/config/filebrowser.db
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 2000M
      reservations:
        cpus: '0.25'
        memory: 256M
