version: '3.6'
services:

   pgadmin-cloud-top:
      image: "{{ helx_registry }}/helxplatform/pgadmin-cloudtop:0.0.3-dev"
      container_name: pgadmin-cloudtop
      entrypoint: /init
      ports:
        - 8080:8080
      volumes:
         - pvc://helx-sidecar-test/sidecar:/sidecar
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 2000M
          reservations:
            cpus: '0.5'
            memory: 2000M
